FROM us.gcr.io/broad-dsp-gcr-public/terra-jupyter-bioconductor:2.0.3

USER root
# This makes it so pip runs as root, not the user.
ENV PIP_USER=false

RUN add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt-get update && apt-get install -yq --no-install-recommends \
    gcc-10 g++-10 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 500 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 500

RUN conda install -y -c conda-forge mamba && \
    mamba install -y -c bioconda \
    samtools bcftools bedtools fcsparser \
    scipy click numba pysam seaborn scikit-learn \
    kb-python && \
    mamba install -y -c conda-forge multicore-tsne hdbscan && \
    mamba install -y -c conda-forge -c bioconda cellrank-krylov && \
    mamba install -y -c anaconda cytoolz && \
    conda clean -afy

RUN pip install scanpy fa2 PhenoGraph pyscenic ngs-tools && \
    pip install flit flit_core && \
    pip install --no-deps harmonyTS palantir doubletdetection && \
    pip install numba colorcet numdifftools

RUN R -e 'BiocManager::install(c("LoomExperiment", "SingleCellExperiment", ask = F))' && \
    R -e 'devtools::install_github("cellgeni/sceasy")' && \
    R -e 'install.packages("reticulate")'

RUN git clone https://github.com/aristoteleo/dynamo-release.git && \
    cd dynamo-release/ && \
    python setup.py bdist_wheel --universal && \
    cd dist/ && pip install dynamo_release-1.0.0-py2.py3-none-any.whl && \
    cd /home/jupyter/ && \
    git clone https://github.com/dpeerlab/SEACells.git && \
    pip install SEACells/ && \
    pip install pyparsing==2.4.2 && \
    rm -rf dynamo-release/ && rm -rf SEACells/

RUN mamba install -y pytorch cpuonly -c pytorch && \
    mamba install -y scvi-tools -c bioconda -c conda-forge && \
    conda clean -afy && \
    pip install harmonypy cdlib

#--prefix /home/jupyter/notebooks/conda_envs/python39
RUN conda create -y -n python39 python=3.9 && \
    . /opt/conda/etc/profile.d/conda.sh && \
    conda activate python39 && \
    mamba install seaborn scikit-learn statsmodels numba pytables ipykernel && \
    mamba install -c conda-forge python-igraph leidenalg && \
    pip install scanpy infercnvpy && \
    python -m ipykernel install --name=python39 --display-name "Python (3.9.9)" && \
    conda clean -afy

ENV NUMBA_CACHE_DIR=/home/jupyter/notebooks/cache/numba_cache
ENV MPLCONFIGDIR=/home/jupyter/notebooks/cache/matplotlib_cache

ENV USER jupyter
USER $USER
# We want pip to install into the user's dir when the notebook is running.
ENV PIP_USER=true

ENTRYPOINT ["/opt/conda/bin/jupyter", "notebook"]